@startuml Definition

class InformationExtractor{
     - constantValues: LinkedHashMap<String, VDMJ::TCValueDefinition>
     - instanceVariables: LinkedHashMap<String, VDMJ::TCInstanceVariableDefinition>

}

abstract class Definition{
     # constantValues: LinkedHashMap<String, VDMJ::TCValueDefinition>
     + returnValue: String = tcDefinition.type.result.toString()
     + name: String = tcDefinition.name.name
     + {abstract} setIfElseSyntaxTree(): void
     + {abstract} parseIfConditions(): void
     # createCompositParameters(element: String): void
     # initializeIfconditions(): void
     # createIfCondition(): void
}

class FunctionDefinition{
     # setIfElseSyntaxTree(): void
     # parseIfConditions(): void
}

class OperationDefinition{
     - instanceVariables: LinkedHashMap<String, VDMJ::TCInstanceVariableDefinition>
     # setIfElseSyntaxTree(): void
     # parseIfConditions(): void
     - setUsedInstanceVariables(): void
}
'note left: tcDefinition->oclIsTypeOf(TCExplicitOperationDefinition)

' left to right direction
VDMJ::TCDefinition <|-- VDMJ::TCExplicitFunctionDefinition
VDMJ::TCDefinition <|-- VDMJ::TCExplicitOperationDefinition

abstract class VDMJ::TCDefinition

Definition "1" *--> "1" VDMJ::TCDefinition: tcDefinition
Definition <|-- FunctionDefinition
Definition <|-- OperationDefinition

FunctionDefinition "1" *--> "1" VDMJ::TCExplicitFunctionDefinition: tcDefinition
OperationDefinition "1" *--> "1" VDMJ::TCExplicitOperationDefinition: tcDefinition

InformationExtractor "1" *--> "0..*" Definition: definitions

@enduml